# Copyright 2020 Google LLC
#
# This software is provided as-is, without warranty or representation for any
# use or purpose. Your use of it is subject to your agreement with Google.

apiVersion: configmanagement.gke.io/v1
kind: Repo
metadata:
  name: repo
spec:
  version: 1.0.0
